// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TranscodeJob {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub video_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub source_bucket: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub source_key: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub targets: ::prost::alloc::vec::Vec<Rendition>,
    #[prost(int64, tag = "6")]
    pub enqueued_at_unix_ms: i64,
    #[prost(int32, tag = "7")]
    pub attempt: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Rendition {
    #[prost(enumeration = "rendition::Resolution", tag = "1")]
    pub resolution: i32,
    #[prost(string, tag = "2")]
    pub container: ::prost::alloc::string::String,
}
/// Nested message and enum types in `Rendition`.
pub mod rendition {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Resolution {
        ResUnspecified = 0,
        Res480p = 1,
        Res720p = 2,
        Res1080p = 3,
        Res4k = 4,
    }
    impl Resolution {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::ResUnspecified => "RES_UNSPECIFIED",
                Self::Res480p => "RES_480P",
                Self::Res720p => "RES_720P",
                Self::Res1080p => "RES_1080P",
                Self::Res4k => "RES_4K",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "RES_UNSPECIFIED" => Some(Self::ResUnspecified),
                "RES_480P" => Some(Self::Res480p),
                "RES_720P" => Some(Self::Res720p),
                "RES_1080P" => Some(Self::Res1080p),
                "RES_4K" => Some(Self::Res4k),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobStatusUpdate {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "job_status_update::Status", tag = "2")]
    pub status: i32,
    #[prost(int32, tag = "3")]
    pub attempt: i32,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub updated_at_unix_ms: i64,
}
/// Nested message and enum types in `JobStatusUpdate`.
pub mod job_status_update {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Status {
        Unspecified = 0,
        Queued = 1,
        Processing = 2,
        Completed = 3,
        Failed = 4,
        Dlq = 5,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "STATUS_UNSPECIFIED",
                Self::Queued => "STATUS_QUEUED",
                Self::Processing => "STATUS_PROCESSING",
                Self::Completed => "STATUS_COMPLETED",
                Self::Failed => "STATUS_FAILED",
                Self::Dlq => "STATUS_DLQ",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "STATUS_UNSPECIFIED" => Some(Self::Unspecified),
                "STATUS_QUEUED" => Some(Self::Queued),
                "STATUS_PROCESSING" => Some(Self::Processing),
                "STATUS_COMPLETED" => Some(Self::Completed),
                "STATUS_FAILED" => Some(Self::Failed),
                "STATUS_DLQ" => Some(Self::Dlq),
                _ => None,
            }
        }
    }
}
