bind 0.0.0.0
protected-mode no
appendonly yes
appendfsync everysec
maxmemory 256mb
maxmemory-policy noeviction
aclfile /etc/valkey/users.acl
tcp-keepalive 300
timeout 0
save 900 1
save 300 10
save 60 10000
